version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgress
    volumes:
      - ./databases:/var/lib/posgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin001
    ports:
      - '5432:5432'

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
